### ISSUE TITLE
Ask me anything related to JavaScript or real life

### ISSUE THREAD

**Issue by andriycraft** [andriycraft/andriycraft#1]

**Comment by BurakKaynakcioglu** [comment]
Hi, im working on functions in c programming nowadays, but my mind confused about something. When the function part uses the "else" part, both of the printf s(one printf is under the function part other one is under the int main)  appear on the console screen. How can i solve this? waiting for your kind reply thanks
![image](https://user-images.githubusercontent.com/116518816/197413914-81643019-3b01-4fbf-921b-3650edd3e1cf.png)
![image](https://user-images.githubusercontent.com/116518816/197414031-09969001-d81a-4cd8-906b-d32ba4701295.png)

**Comment by andriycraft** [comment]
> Hi, im working on functions in c programming nowadays, but my mind confused about something. When the function part uses the "else" part, both of the printf s(one printf is under the function part other one is under the int main) appear on the console screen. How can i solve this? waiting for your kind reply thanks

stackoverflow.com
